### PR TITLE
feat: 全站广告屏蔽

### LINKED ISSUE #14: Remove Ads
Ads

### PR DESCRIPTION
**Pull request by Mesimpler**
close #14 
[](https://postimg.cc/bGR3Sh8c)

### CODE REVIEW

**Comment by 0xlau** [comment]
Thank you very much for your contribution. I will review it later.

**Comment by 0xlau** [comment]
It does not work.
image

**Comment by Mesimpler** [comment]
fixed, please recheck.

**Comment by 0xlau** [comment]
It still does not work.
image

**Pull request closed without merging**
