### PR TITLE
feat: Hide Bilibili hot searches & Press Esc to exit image preview (#12 & #13)

### LINKED ISSUE #12: Hide Bilibili hot searches in the search box
hide

### LINKED ISSUE #13: Press Esc to exit image preview
Unable to close image preview by pressing the Esc key.

image preview

### PR DESCRIPTION
**Pull request by coco-w**
close #12 
close #13 

image

### CODE REVIEW

**Comment by 0xlau** [comment]
1. If history record is empty, bottom height of the search box should be 0px.

image

2. In the video page, it does not work.

image

**Comment by coco-w** [comment]
> 1. If history record is empty, bottom height of the search box should be 0px.
> 
> image
> 
> 2. In the video page, it does not work.
> 
> image

it's fix

**Comment by coco-w** [comment]
Sorry, I made an unrelated commit on this issue, but it was already pushed when I noticed

**Comment by 0xlau** [comment]
> Sorry, I made an unrelated commit on this issue, but it was already pushed when I noticed 😭

It's fine. 😄 Just pay more attention next time.

**Pull request merged**
